[package]
name = "bicamrl-gui"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = { version = "0.13", features = ["tokio", "debug"] }
tokio = { version = "1", features = ["rt", "macros"] }
reqwest = { version = "0.12", features = ["json", "stream"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "1.11", features = ["v4", "serde"] }
rand = "0.8"
futures = "0.3.31"

[[bin]]
name = "bicky-gui"
path = "src/main.rs"
